server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhk.springcloud.entities

eureka:
  client:
    register-with-eureka: true  # 把自己注册进eurekaServer中
    fetch-registry: true        # 是否从eurekaServer中抓取已有的注册信息，必须开启才能配合Ribbon使用负载均衡
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka