server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:        # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:   # 定义的名称，用于binding整合
          type: rabbit   # 消息组件类型
          enviroment:    # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 101.200.49.246
                port: 5672
                username: guest
                password: guest    # guest用户不允许远程访问
      bindings:           # 服务的整合处理
        - output:           # 通道名称
          destination: studyExchange   # 要设置的exchange名称
          content-type: application/json  # 消息类型
          default-binder: defaultRabbit    # 绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 心跳时间及间隔
    lease-expiration-duration-in-seconds: 5
    instance-id: send-8001.com
    prefer-ip-address: true