server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.49.246:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
