server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false      # 关闭自我保护机制
    eviction-interval-timer-in-ms: 2000  # 间隔时间为2秒
  instance:
    hostname: eureka7001.com     # eureka服务器的实例名
  client:
    register-with-eureka: false  # 不向注册中心注册自己
    fetch-registry: false        # false表示自己为注册中心，而不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      # 设置与eureka server交互的地址查询服务和注册服务
      # defaultZone: http://eureka7002.com:7002/eureka/

